# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

#general
SECRET_KEY_BASE: 3185d118895017b599f9fc475746c8d3870be2a516cb3017da6b87d50ac376f45920e8b899057d489fcdcec33515ada2b408c19963364803cffe2ef6486014e9

#database
DATABASE_PRODUCTION_USERNAME: arima
DATABASE_PRODUCTION_PASSWORD: arima

#admin creds
ADMIN_NAME: admin
ADMIN_PSWD: admin

#email
ACTION_MAILER_ADDRESS: fill_me
ACTION_MAILER_PORT: fill_me
ACTION_MAILER_USERNAME: fill_me
ACTION_MAILER_PASSWORD: fill_me

#devise
DEVISE_SECRET_KEY: e2ac574d23c2e91701a106734d6f04b7b358f4e54749b1f82f657891f9bd00ae24015540da01d60f8f1ca5c81e44a2b0ba04dfe04c6c3b9e166cd53843b39014
